name: Project Submission
description: "Share your project with us to get a digital badge and win exciting prizes!"
title: "Project: <short description>"
body:
  - type: input
    id: name
    attributes:
      label: Project name
      description: Name of your project
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a short description of your project. What is it about? What type of app have you built? What is it doing? What problem is it solving?
    validations:
      required: true
  - type: checkboxes
    id: categories
    attributes:
      label: What type of app did you build in this hackathon?
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
       - label: Enterprise focused = A Teams tab with SPFx
       - label: AI focused = A Teams bot or message extension that integrates with Teams Conversational AI
       - label: Multi-hub focused = A Teams app that works across Outlook and M365 app
       - label: Productivity focused = A Teams app that connects with Microsoft 365 data through SSO and Microsoft Graph
  type: checkboxes
    id: language
    attributes:
      label: Which language did you use to build your app?
      description: Select one only.
      options:
        - label: .NET
        - label: JavaScript/TypeScript
  - type: input
    id: url
    attributes:
      label: Repo URL
      description: URL of the GitHub repo with your project
    validations:
      required: true
  - type: input
    id: video
    attributes:
      label: Project video
      description: A short demo video of your project
    validations:
      required: true
  - type: input
    id: teammembers
    attributes:
      label: Team members
      description: Comma-separated list of GitHub users who worked on this project
    validations:
      required: true
