name: Project Submission
description: "Share your project with us to get a digital badge and win exciting prizes!"
title: "Project: <short description>"
body:
  - type: input
    id: name
    attributes:
      label: Project name
      description: Name of your project
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a short description of your project. What is it about? What type of app have you built? What is it doing? What problem is it solving?
    validations:
      required: true
  - type: dropdown
    id: Categories
    attributes:
      label: Which technologies did you use in your project? (Select multiple if needed)
      multiple: true
      options:
        - Teams Toolkit for Visual Studio Code
        - Teams Toolkit for Visual Studio
        - Teams Conversational AI Library
        - SPFx
        - Microsoft Graph
        - Cognitive Services
        - Azure Functions
  - type: input
    id: url
    attributes:
      label: Repo URL
      description: URL of the GitHub repo with your project
    validations:
      required: true
  - type: input
    id: teammembers
    attributes:
      label: Team members
      description: Comma-separated list of GitHub users who worked on this project
    validations:
      required: true
