name: Project Submission
description: "Share your project with us to get a digital badge and win exciting prizes!"
title: "Project: <short description>"
body:
  - type: input
    id: name
    attributes:
      label: Project name
      description: Name of your project
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a short description of your project. What is it about? What type of app have you built? What is it doing? What problem is it solving?
    validations:
      required: true
  - type: dropdown
    id: Categories
    attributes:
      label: What type of app did you build in this hackathon?
      multiple: false
      options:
       - Enterprise focused: A Teams tab with SPFx
       - AI focused: A Teams bot or message extension that integrates with Teams Conversational AI
       - Multi-hub focused: A Teams app that works across Outlook and M365 app
       - Productivity focused: A Teams app that connects with Microsoft 365 data through SSO and Microsoft Graph
  - type: input
    id: url
    attributes:
      label: Repo URL
      description: URL of the GitHub repo with your project
    validations:
      required: true
  - type: input
    id: video
    attributes:
      label: Project video
      description: A short demo video of your project
    validations:
      required: true
  - type: input
    id: teammembers
    attributes:
      label: Team members
      description: Comma-separated list of GitHub users who worked on this project
    validations:
      required: true
